### ISSUE TITLE
example.php

### ISSUE THREAD

**Issue by HeikoMamerow** [autocompletejs/autocomplete.js#1]
Bonjour Baptiste,
sorry, i do not understand clearly, how to bring (indexing?) the content from my website into the autocomplete-suggestions.... Can you please show the example-script from your demo website? I would like to find out, how you wrote this.

I mean this example-script:
http://autocomplete-js.com/1.5/example.php

Tnx & greetings from Berlin!
:-)

**Comment by baptistedonaux** [comment]
Hi @HeikoMamerow,

Thank you for the link (I have fix the PHP warning).

To response at your question, the PHP script isn't really important.

The request send (in my case) a GET parameter ```q``` (/1.5/example.php?q=…) and the response must be a JSON.

Example : 
```php
<?php

$query = $_GET["q"];

// Execute your workflow, SQL, array PHP or other
$results = …

// $results => array(
//    url1 => title1,
//    url2 => title2,
//    url3 => title3,
// );

echo json_encode($results);
```

My script looks like.
