### ISSUE TITLE
Mobile Issue

### ISSUE THREAD

**Issue by suncoastkid** [autocompletejs/autocomplete.js#12]
On Android, Firefox 40.0, keyup event not triggering on mobile without entering a space after the search term.

**Comment by baptistedonaux** [comment]
Hi and thank you for tour feedback. Can You describe your environnement ?

* Phone OS
* Browser
* brower version

Do You have an website where I can test your problem ?

**Comment by baptistedonaux** [comment]
No response and new release. Done.
