### ISSUE TITLE
Highlight matched text

### ISSUE THREAD

**Issue by adaniello** [autocompletejs/autocomplete.js#13]
Why not highlight matched text? For example, with a simple "strong" tag, or better with a custom class.

Thanks

**Comment by baptistedonaux** [comment]
I @adaniello 
Thank you for this question because it's really important to propose this feature. I work actually on the version 2 and I add immediately the feature in the next major milestone.

**Comment by baptistedonaux** [comment]
Lack of time to develop this feature. Postponed to the next roadmap.

**Comment by ScherlOMatic** [comment]
This feature is definetly a must have but you can also achieve this by doing some code in your business logic.
Before passing the data you can iterate over your object and do something like this:
` $mark = str_ireplace($query, '<b>' . $query . '</b>', $item);`
Don't forget to do a json_encode in the end.

**Comment by adaniello** [comment]
@ScherlOMatic thanks for sharing.
I do as well, but i'ld like to have response data without html tags so i hope @baptistedonaux will have time to solve it (maybe i'll find time to solve this issue).

**Comment by baptistedonaux** [comment]
Hi @adaniello @ScherlOMatic !

The autocomplete.js offers a simple tool without custom comportment. I'm not sure to want develop this feature for this reason :

-autocomplete.js offer an interface to display results, not code to filter results.
- The filtering is applied by the server, so if I write UK (in the example documentation) I can think that United Kingdom will be display. But it's impossible to define a rule to make an highlight on U and K (**U**nited **K**ingdom)

Currently, the best response is written by @ScherlOMatic. The filtering is realize by server so the highlight must be realize by the server. Only it knows the filtering strategy.

In the future (and when I will have time), I add a function **_Highlight** in the code (which can be overrided) to make an simple highlight.

**Comment by baptistedonaux** [comment]
Feature implemented into 2.1. Released quickly.
