### ISSUE TITLE
Reset input field after selection

### ISSUE THREAD

**Issue by dedan** [autocompletejs/autocomplete.js#21]
I use an input field with autocomplete.js to populate entries in a list. You could see this as similar to adding tasks to a list in a TODO application. In order to add multiple items in a row, I want to clear the input field after an entry from the autoselect list got selected. How can I achieve this?

So far I tried selecting the DOM node via javascript and simply setting its `.value` property to an empty string. It first looks like this would do the trick, but when I click anything outside of the input field, the previously selected value re-appears.

**Comment by baptistedonaux** [comment]
Hello and sorry the response time.

I'm not sure to understand your problem. You want item in your input without reset the last content or do you want reset this input field when you select a new item ?

**Comment by dedan** [comment]
I already found a solution. Thanks for your response
