### ISSUE TITLE
Keyboard Enter without selecting an item.

### ISSUE THREAD

**Issue by ScherlOMatic** [autocompletejs/autocomplete.js#22]
Hello!

I'd like to have your awesome plugin plus the ability to use the "enter/return" button without selecting one of the autocomplete items.
If i write a few letters within my input field, I can see the suggestions below but when i press return nothing happens.

Is there a workaround or something else you can help me with?

thx in advance stefan

**Comment by baptistedonaux** [comment]
Hello and sorry for waiting, I miss time.

So I resume, you want write letters in the autocomplete field, and without selected items, when I push enter button, one or all fields will be added in the input.

Currently when I see suggestions and I push enter button without selected one item, no action executed.

**Comment by baptistedonaux** [comment]
Wow, I don't know why this issue has been tagged fike a « Bug ». Do you have resolve your problem ?

**Comment by ScherlOMatic** [comment]
Hello!
I am using another plugin atm. But I will give it a try.
Let you know asap.

see u

**Comment by baptistedonaux** [comment]
Could you given the project URL ?
