### ISSUE TITLE
Simple "copy & paste" error in docs

### ISSUE THREAD

**Issue by adaniello** [autocompletejs/autocomplete.js#23]
Hi,
only now i note that in your doc there's a stupid error:  about "QueryArg" in column "Override HTML declaration" you pasted the "HttpMethod" sample.

It's all

**Comment by baptistedonaux** [comment]
Thank you for your returns, I fix it the next week !

**Comment by baptistedonaux** [comment]
The documentation available at this URL (http://autocomplete-js.com) is now hosted by GitHub. The documentation can be edited in this repository [autocompletejs/autocompletejs.github.io](http://github.com/autocompletejs/autocompletejs.github.io).

You can help me in sending a PR.

Thanks.

**Comment by baptistedonaux** [comment]
@adaniello Can you confirm this issue has been fixed ?

**Comment by baptistedonaux** [comment]
Merged ! Thanks !
