### ISSUE TITLE
QueryArg via data attribute not works

### ISSUE THREAD

**Issue by adaniello** [autocompletejs/autocomplete.js#24]
Hi,
we could set "QueryArg" via "data-autocomplete-param-name" attribute but not works.

To fix this issue, i think you should change the line 500 in:

`queryParams = params._QueryArg() + "=" + params._Pre();`

So this call the workflow method in place of the settings param.

Regards

**Comment by adaniello** [comment]
Fix proposal at #25

**Comment by baptistedonaux** [comment]
Of course, Merged ;-) Thank you
