### ISSUE TITLE
After entering the data and press /select last item using up arrow then focus goes to starting point on the search box

### ISSUE THREAD

**Issue by irfanlbrce** [autocompletejs/autocomplete.js#26]
<img width="1324" alt="screen shot 2016-07-12 at 11 01 05 am" src="https://cloud.githubusercontent.com/assets/10115931/16771947/4d56a214-4820-11e6-8dcb-0fd66a50c5ed.png">

After entering the data and press /select last item using up arrow then focus goes to starting point on the search box and not taking result from auto complete.

**Comment by baptistedonaux** [comment]
Thank you for your feedback. I'm working on next release. I must identify if it's a fail of documentation or library.

**Comment by baptistedonaux** [comment]
Fixed
