### ISSUE TITLE
Search isn't triggered with only one character

### ISSUE THREAD

**Issue by ediblemanager** [autocompletejs/autocomplete.js#27]
Hi,

I might be getting this wrong, but it seems from the example country search on the main page and in my own implementation that triggering a search with one character now doesn't happen (it worked in version 1.7, but in version 2+, it seems to no longer work).

Any advice?

Cheers

**Comment by baptistedonaux** [comment]
Hi @ediblemanager ,

Thank you for your feedback ! I'm currently working on release 2.1. I test that and I fix it.

**Comment by ediblemanager** [comment]
@baptistedonaux great! Thanks for making this library. Your work is appreciated!

**Comment by baptistedonaux** [comment]
Hi, I have "isolate" the fail. Currently, the keydown event is used whereas the last value is returned. In any case, the previous value was search.

Fixed in 2.1, thank you for your feedback !

**Comment by ediblemanager** [comment]
@baptistedonaux Thanks for your work!
