### ISSUE TITLE
Possibilité de sélectionner la première proposition

### ISSUE THREAD

**Issue by Metrakit** [autocompletejs/autocomplete.js#28]
Bonjour,
Merci tout ta lib !

J'ai une petite question, est-il possible de sélectionner automatiquement la 1ere proposition dans l'auto-complétion ?

**Comment by baptistedonaux** [comment]
Hi @Metrakit and thank you for your encouragements.

Without override the code, this feature is unavailable but you can easily rewrite the method [**_Render**](http://autocomplete-js.com/#_Render).

``` js
AutoComplete({
  _Render: function(response) {
            // Code base
            var ul;

            if (typeof response == "string") {
                ul = this._RenderRaw(response);
            } else {
                ul = this._RenderResponseItems(response);
            }

            if (this.DOMResults.hasChildNodes()) {
                this.DOMResults.removeChild(this.DOMResults.childNodes[0]);
            }

            this.DOMResults.appendChild(ul);

            // Specific rule
           this._Select(this.DOMResults.querySelector("li:first-child"));
  }
});
```

I don't have tested but your case seems simple. Send me a feedback Please ;-)

**Comment by Metrakit** [comment]
Thanks ! I'm going to try that
