### ISSUE TITLE
no demos

### ISSUE THREAD

**Issue by lygstate** [autocompletejs/autocomplete.js#3]

**Comment by baptistedonaux** [comment]
Hi, many people asks me examples but I don't understand what is missing in the documentation.

There is one example in the documentation (client integration). Is it server integration who miss you or other ?

**Comment by adis-me** [comment]
Would love to see some different templates, is it even possible? I can not answer that question without installing an trying out your library. But it looks nice!

**Comment by baptistedonaux** [comment]
Thank you for feedback ! I will work on few examples ;)

**Comment by baptistedonaux** [comment]
I will add a live demo on the next website/documentation with the release 2.0.

**Comment by alexandrursu** [comment]
Yes, please share back-end PHP script for that is used for query filtering

**Comment by baptistedonaux** [comment]
Yes, it is planned for the output autocomplete.js 2.x. Currently rewriting.

**Comment by alexandrursu** [comment]
:( I am trying to implement it now, very helpful but very bad documented finally will need to try something else.

1. provide JSON example
2. Provide back-end script (will be nice everything to be in JS)
3. Make a separate demo or include it in downloadable ZIP

Thanks!

**Comment by baptistedonaux** [comment]
The documentation takes HTML or JSON response.

JSON can be an array or an object. The response structure must match this :

For a JSON array
```json
["USA", "UK", "Germany", "France"]
```

For a JSON object
```json
{
    "usa": "United States of America",
    "uk": "United Kingdom",
    "de": "Germany",
    "fr": "France"
}
```

> very bad documented
>
> -- <cite>@alexandrursu</cite>

The documentation explains the JS implementation. Autocomplete.js 
is not specially coded for PHP dev. Please take mana or propose documentation add-on before critic open-source project.
