### ISSUE TITLE
Possible to override clicking an item?

### ISSUE THREAD

**Issue by MorningZ** [autocompletejs/autocomplete.js#30]
I'm using this great plugin to to an autocomplete for contacts, generally in the form of:

```
<ul>
      <li>
            <address>
                  <div class="Name">John Smith</div>
                 <div class="Email"><a href="mailto:jsmith@company.com">jsmith@company.com</a></div>
                 <div class="Phone">(555) 555-1212</div>
            </address>
      </li>
</ul>
```

I'd like to be able to cancel "selecting" the item (and filling in the input field) and just make that email address hyperlink work and then manually call "_Blur" to close the autocomplete results

Is that possible?  I tried to override the "_Select" method, which allowed me to not fill in the <input> field, but it still closes the ul and doesn't let me follow that hyperlink

**Comment by cinan** [comment]
Try overriding _Blur function with this:

```
var params = this;
setTimeout(function() {
  params.DOMResults.setAttribute('class', 'autocomplete');
}, 150)
```

Effectively it ignores `now` parameter and always delays closing the autocomplete.

**Comment by baptistedonaux** [comment]
@MorningZ @cinan The best solution isn't to lock ```_Blur``` function because, the results list will be never closed. To catch neatly this behavior, it should have the ```event``` and call ```event.preventDefault();```.
