### ISSUE TITLE
Configuring KeyBoard Mappings

### ISSUE THREAD

**Issue by omissis** [autocompletejs/autocomplete.js#34]
It would be nice to be able to customize Keyboard Mappings to implement more advanced behaviours and modify existing ones. For example I can't see a way to bind the ESC key that doesn't require some heavy hacking with the internals.

Any thoughts/suggestions?

**Comment by baptistedonaux** [comment]
There is [**KeyboardMappings**](https://github.com/autocompletejs/autocomplete.js/blob/2.1/src/autocomplete.ts#L117) option (which isn't describe in the documentation 😞).

I think you can merge the default configuration with your custom mapping.

```js
var mapping = Object.assign(AutoComplete.defaults.KeyboardMappings, {
    "ESC": { … }
});

AutoComplete({
    KeyboardMappings: mapping
});
```

**Comment by omissis** [comment]
ah that's cool, thanks. I'll try that and see if I can add that to the docs :)

**Comment by omissis** [comment]
@baptistedonaux ok the suggestion works, with the only issue that ConditionOperator is not exposed, so it's not possible to use it as in the core definitions. Since my use case is rather simple, I managed to add it anyway, but it should probably be fixed. Should I open a ticket for that? (Maybe I will also manage to push a PR, but that'll take some more time)
