### ISSUE TITLE
this._Limit() Not Enforced

### ISSUE THREAD

**Issue by oahdoot** [autocompletejs/autocomplete.js#36]
It seems that `this._Limit()` is not enforced on the results. I am not sure if this is by design, but I would assume that the limit would be imposed on the rendering of the response, so that the `<ul>` would only contain a set amount of results (the limit).

**Comment by baptistedonaux** [comment]
Thank you for your report but I come just fixed this bad comportment with PR #32.

Could you confirm me that issue is fixed ?

**Comment by oahdoot** [comment]
Excellent turnaround! It works perfectly, but I noticed one quirk: If you don't have a `Limit` set, then the default is `0`. This doesn't make sense to me, since it would stand to reason that by default, autocomplete should display **all** of the results (the length of `response.length`). Perhaps `Limit` should be `undefined` by default, and if there is no `Limit` supplied, it should default to the size of `response.length`?

**Comment by baptistedonaux** [comment]
```Limit``` default value could be ```undefined``` but the code works today. All parameters follows the same logic.

Thank you for your feedback !
