### ISSUE TITLE
Results stay in place after window resize

### ISSUE THREAD

**Issue by csakip** [autocompletejs/autocomplete.js#37]
The result dropdown is placed on initialization and stay there. If you resize the window, it should recalculate its position.
I tried to call _Position() after resize but that gives a new default dropdown and keeps the original too.

**Comment by csakip** [comment]
Any repositioning of the parent input results this. If I resize a div above it and it is pushed down, the dropdown stays in its original position.

**Comment by baptistedonaux** [comment]
Hi and sorry for the response time !

An event can be throw to recalculate the result element position.

```js
var event = new CustomEvent("position");
document.querySelector(…).dispatchEvent(event);
```

**Comment by joelataylor** [comment]
This helped me, thank you!

**Comment by pulzarraider** [comment]
This should be build in feature inside this autocomple library.
