### ISSUE TITLE
Custom headers support

### ISSUE THREAD

**Issue by davidchase** [autocompletejs/autocomplete.js#4]
Hi great simple autoComplete thanks for the work :+1: 
I was wondering if its possible to allow to pass in custom headers, I see in the [source](https://github.com/autocompletejs/autocomplete.js/blob/master/src/autocomplete.js#L263) you only set one, in my case it would be great to be able to add multiple headers in order for me to do a `GET` on the URL. 

Let me know if you want to do this or not... or if I should submit a PR 

cheers david

**Comment by baptistedonaux** [comment]
Hi @davidchase and thank you for your feedback.

This feature is interesting and I think others people will be interested to customize any headers.

I add this feature in the next release. I will develop the feature and I integrate it for the 1.7 release.

**Comment by davidchase** [comment]
Awesome thanks :+1:

**Comment by baptistedonaux** [comment]
A new version (1.7.0) is bumped and build. You can find the documentation updated here.

http://autocomplete-js.com/#headers
