### ISSUE TITLE
Pressing 'Enter' cannot hide the select dialog

### ISSUE THREAD

**Issue by scotv** [autocompletejs/autocomplete.js#5]
Hi @baptistedonaux, thanks for your lightweight autocomplete.js.

When I left-click an item I want to select:

0. item value will insert into the `input[autocomplete]`
0. select dialog will be disappear / hidden

However, when I press `Enter` key on the item I want to select:

0. item value will insert into the `input[autocomplete]`
1. select dialog __STILL__ shows up

Here is the reason of this issue:

```JavaScript
if (keyCode == 13 && attr(result, "class").indexOf("open") != -1) {
    // if press Enter, we select the item
    self._args.select(input, liActive);
    // then hide the select dialog
    attrClass(result, "autocomplete");
}

if (keyCode == 38 || keyCode == 40) {
    // key Up and Down
} else if (keyCode < 35 || keyCode > 40) {
    // keyCode of Enter is 13
    if (inputValue && custParams.url) {
        if (!dataAutocompleteOldValue || inputValue != dataAutocompleteOldValue) {
            // __ATTENTION HERE__
            // So that the select dialog shows up again
            attrClass(result, "autocomplete open");
        }

        request = ajax(request, custParams, custParams.paramName + "=" + inputValue, input, result);
    }
}
```

So that I think the code 
`else if (keyCode < 35 || keyCode > 40)`
may need be changed into 
`else if (keyCode != 13 && (keyCode < 35 || keyCode > 40))`

see revision [a36f56d](https://github.com/scotv/autocomplete.js/commit/a36f56d31718a00df0fdf354c04439ace055e454)

**Comment by baptistedonaux** [comment]
Hi @scotv !

Thank you for this analyse ! I look your demonstration and your fix tomorrow and I come back to you.

**Comment by baptistedonaux** [comment]
I tried your fix and it's perfect. You can send a pull request.
