### ISSUE TITLE
query argument customizing

### ISSUE THREAD

**Issue by ghost** [autocompletejs/autocomplete.js#59]
Hello, the REST API to which I'm sending the query only accepts the following format:
`/api?<field>=<operator>.<query string>`

for instance if I were to search for the name of a person named Roger:
`/api?name=ilike.roger`

I have declared my search argument as `"name=ilike."` however it looks like the "=" in my search argument is percentage coded to %3D and an equal sign is stuck before my query string:
`/api?name%3Dilike.=roger`

which of course results in a bad request.

Is it possible to customize the style of query beyond changing just the query "word"?

Thanks in advance!

**Comment by baptistedonaux** [comment]
Hi !

You can use [`_Pre`](http://autocomplete-js.com/#_Pre) method to override value sent.

With this way, you can keep field with value `name`.
