### ISSUE TITLE
Suggestion on Key/Value support for autocomplete.js

### ISSUE THREAD

**Issue by scotv** [autocompletejs/autocomplete.js#6]
Hi @baptistedonaux, 

for default HTML `<select>/<option>`, we have:

```HTML
<select>
<option value="key001">display value 001</option>
<option value="key002">display value 002</option>
<option value="key003">display value 003</option>
</select>
```

Currently, I think your autocomplete.js only supports a simple display value, but sometimes I want:
```HTML
<ul>
<li value="key001">display value 001</li>
<li value="key002">display value 002</li>
<li value="key003">display value 003</li>
</ul>
```

I made little changes (see [e381632] [1]), so that we can display the value of item, and store the key of item into the `input[data-autocomplete]`:

```HTML
<input data-autocomplte="/" .... data-autocomplete-item-key="key002" />
<ul></ul>
```

Also, each JSON item is an `Object`, not just a `string`, so we may need `keyOfJSON()` and `valueOfJSON` to allow user to customize the key and display value. (also see  [e381632] [1]).

By the way, my solution may not be the best one, you can use your code style in your own way, and I will keep following your codes.

Thanks.

[1]: https://github.com/scotv/autocomplete.js/commit/e38163219b04063e0dec6d46cc6dcf4660c5f8e5  "scotv/commit"

**Comment by baptistedonaux** [comment]
Hi @scotv

It's a good feature but I think that develop this feature before 2.0 release is a bad idea.

For the rewrite (2.0) I think use TypeScript. So develop this feature now can be a time investissement really important.

Personally, I don't develop this feature but if you want send a pull request, I will be happy te accept it for a new version.

**Comment by baptistedonaux** [comment]
After much thought, this good idea doesn't integrate (for the moment) because the project purpose is giving a simple text autocomplete.js, similarly at jQuery UI Autocomplete.

Replace basic DOM with ul/li by select/option isn't necessary. More, the display of this element complexity the project.

Today, the capital gain is limited, so I prefer concentrate my effort on a simple script.

Best Regards, Baptiste
