### ISSUE TITLE
When item is selected input remains empty

### ISSUE THREAD

**Issue by madisamou** [autocompletejs/autocomplete.js#60]
I am having a problem with selecting an item returned by the autocomplete.
I write some letters, see some suggestions and when i click one of them, nothing happens, the input field remains empty.
Problem encountered on both mobile and desktop.

Have you an idea about this issue ?

Thanks

**Comment by sondr** [comment]
I have the same issue. The first two  items shown in  the list works, but none after those two. I think it might have to do with the height of the elment where autocomplete is inserted.

**Comment by sondr** [comment]
My issue was resolved by following the proposed fix in first post [here](https://github.com/autocompletejs/autocomplete.js/issues/29)

**Comment by baptistedonaux** [comment]
https://github.com/autocompletejs/autocomplete.js/issues/29#issuecomment-414577500
