### ISSUE TITLE
Key press up and down may not work in v1.6.0

### ISSUE THREAD

**Issue by scotv** [autocompletejs/autocomplete.js#7]
Hi @baptistedonaux,

In your v1.6.0, you have:

```JavaScript
 function attrClass(item, value) {
     if (item) {
        return attr(item, !value ? "class" : {"class": value});
     }
 }
```

but when you  try to remove `class="active"` by using `attrClass(liActive, "")` when pressing key up or down. It may not work.
```JavaScript
attrClass(liActive, "") // then
attr(liActive, "class") // then in your attr()

try {
  for(var key in "class") {
      item.setAttribute(key=0, value="c");  // throw Error
  }
} catch {/*return the class name of item*/}
```

__In fact, you have changed your `attrClass` in revision e782083, this change also fixed this issue.__

I am wondering why the key press up and down works in you demo website, maybe you use a different version `autocomplete.min.js`, instead of the v1.6.0 `autocomplet.js`

**Comment by baptistedonaux** [comment]
Hi @scotv 

Already fix it in 1.7.0 release.

But thank you for your feedback.
