### ISSUE TITLE
How to use directly without NPM?

### ISSUE THREAD

**Issue by pratham2003** [autocompletejs/autocomplete.js#70]
I'm using WordPress and want to include this script only on one single page.
How can I do that? If I use the js file directly I get AutoComplete is undefined error.

**Comment by arnolem** [comment]
You can download the lastest version here :
https://github.com/autocompletejs/autocomplete.js/releases

**Comment by baptistedonaux** [comment]
You can try to use [GitHub releases link]( https://github.com/autocompletejs/autocomplete.js/releases). No CDN are provided.
