### ISSUE TITLE
How to Override Method

### ISSUE THREAD

**Issue by Chemtron** [autocompletejs/autocomplete.js#77]
I would like to keep the AutoComplete.js unaltered and override a method like _Post.
I have tried:
AutoComplete();
AutoComplete._Post = function(response) { mycode }
and 
AutoComplete.prototype._Post = function(response) { mycode }

Javascript does not replace the method and calls the original method instead. My apologies my js is not expert enough to resolve this. How is this best done?

Thank you!

**Comment by baptistedonaux** [comment]
[You can follow example given in documentation.](http://autocomplete-js.com/#_Post).

```js
AutoComplete({
    _Post: function(response) {
       // your code…
   }
})
```
